- name: Remove default site from sites-available
  ansible.builtin.file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: Create nginx site config
  ansible.builtin.copy:
    dest: "/etc/nginx/sites-available/{{ app_domain }}"
    content: |
      server {
          listen 80;
          server_name {{ app_domain }};

          location / {
              proxy_pass http://127.0.0.1:{{ redmine_port }};
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }
    owner: root
    group: root
    mode: "0644"

- name: Remove default site from sites-enabled
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create symlink for nginx site
  ansible.builtin.file:
    src: "../sites-available/{{ app_domain }}"
    dest: "/etc/nginx/sites-enabled/{{ app_domain }}"
    state: link

- name: Replace nginx.conf
  ansible.builtin.copy:
    dest: /etc/nginx/nginx.conf
    content: |
      events {
          worker_connection 1024;
      }

      http {
          include /etc/nginx/sites-enabled/*
      }
    owner: root
    group: root
    mode: "0644"

- name: Test nginx configuration
  ansible.builtin.command: nginx -t

- name: Reload nginx
  ansible.builtin.command: nginx -s reload
