- name: Deploy Docker
  hosts: webservers
  become: true
  gather_facts: true
  tags: [docker]

  roles:
    - docker

- name: Deploy Redmine application
  hosts: all
  become: true
  tags: [deploy]

  roles:
    - redmine

- name: Setup nginx
  hosts: webservers
  become: true
  gather_facts: true
  tags: [nginx]

  roles:
    - nginx

- name: Deploy Datadog agent
  hosts: webservers
  become: true
  gather_facts: true
  tags: [datadog]

  roles:
    - datadog
