ansible_user: kirillt
ansible_ssh_private_key_file: ~/.ssh/ssh-key-1765287244855

install_docker: false
redmine_port: 8080
app_domain: ktarasenko.online

db_database: "{{ vault_db_database }}"
db_username: "{{ vault_db_username }}"
db_password: "{{ vault_db_password }}"
db_port: "{{ vault_db_port }}"
