db_postgres: rc1b-q4h3jvp0nm6d9ooh.mdb.yandexcloud.net,rc1d-l9bhdkotte5q34dl.mdb.yandexcloud.net
db_database: db1
db_username: kirillt
db_password: ZFRgwc86QsL2EEa
db_port: 6432
vault_datadog_api_key: 88a2bf08e5940eae2a7a6bdcf9dc9833

ansible_user: kirillt
ansible_ssh_private_key_file: ~/.ssh/ssh-key-1765287244855

install_docker: false
redmine_port: 8080
app_domain: ktarasenko.online
