$ANSIBLE_VAULT;1.1;AES256
63323935646439613433626662366565643835383764316137343766316261353064373336323230
3235326333653664306235653465373431323539653433300a356534613163366639386336396134
33653734353764653636646534666435616331383736393161343066393066313438373839646632
3638343638366465610a303134386366333563383861643265646234666464316136353964303632
38666462663838616530336339313339613961666165383737393065366664383938663165313934
65643237633239363665303431376636353062623034323939373131346430626536396363393839
35393763353065383934623437653131643730613030363236663132383465323432653936346166
34633166343432616332373338353739316238613730633030333033633065396437663165306466
65383434633661646338316630303163643338303934613863386132306534623931306634316430
61616162333861663664366661303333616434666433396138636636323830633032623465383761
30373237633039306635306162323332316532316466653262316462336334616665616638313238
38326431663461393663363335346631386532623838343362656137663366353436623137666663
38333833366362666336363461333733383039633631306430343264396633306631
